### ISSUE TITLE
Doesn't work with Nuxt 3 rc.1 in production build

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt-community/supabase-module#29]
### Environment
```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.3.1`
- Builder:          `vite`
- User Config:      `buildModules`, `ui`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/supabase@0.1.9`, `@nuxthq/ui@0.0.2-27508221.57354f6`, `@nuxtjs/color-mode@3.0.2`
------------------------------
```

### Reproduction Link

Official demo: https://github.com/nuxt-community/supabase-module/tree/main/demo

### Steps to reproduce
1. Upgrade Nuxt to `3.0.0-rc.1` (official migration guide: https://github.com/nuxt/framework/discussions/4479)
2. `npm run build`
3. `npm start` 

### What is actually happening?
```
Listening on http://0.0.0.0:3000/
[nuxt] [request error] require() of ES Module supabase-module/demo/.output/server/node_modules/node-fetch/src/index.js from supabase-module/demo/.output/server/node_modules/cross-fetch/dist/node-ponyfill.js not supported.
Instead change the require of index.js in supabase-module/demo/.output/server/node_modules/cross-fetch/dist/node-ponyfill.js to a dynamic import() which is available in all CommonJS modules.
  at Object.<anonymous> (./.output/server/node_modules/cross-fetch/dist/node-ponyfill.js:1:19)  
  at async Promise.all (index 0)  
  at async ./.output/server/chunks/handlers/renderer.mjs:544:24  
  at async ./.output/server/chunks/handlers/renderer.mjs:601:20  
  at async ./.output/server/node_modules/h3/dist/index.mjs:417:19  
  at async Server.nodeHandler (./.output/server/node_modules/h3/dist/index.mjs:367:7)
```

In my private project, I have the same problem after building the app. But everything (`user`/`auth` & `client`) works fine in dev mode.

**Comment by mwohlan** [comment]
In the nuxt config defineNuxtConfig has to be imported from nuxt and not nuxt3 since the rc version. Did you use the most up to date version (0.1.9) ?

**Comment by lukaszflorczak** [comment]
> In the nuxt config defineNuxtConfig has to be imported from nuxt and not nuxt3 since the rc version

Yes, I know. I linked migration guide.

> Did you use the most up to date version (0.1.9) ?

As I mentioned: `@nuxtjs/supabase@0.1.9`

**Comment by larbish** [comment]
Can you try with the last version I just pushed (`0.1.10`). I have updated the demo, should works too. Let me know !

**Comment by lukaszflorczak** [comment]
Unfortunately it didn't fix my problem. I tested it once again with demo from the module, and I found the problem only exists if `npm` is used as package manager. It works with `yarn`. 

I also found that in build stage `npm` reports a warn:

```
 WARN  Multiple major versions of package node-fetch are being externalized. Picking latest version.                                                                                                                         22:14:07
  - ./supabase-module/demo/node_modules/node-fetch@2.6.7
  - ./supabase-module/demo/node_modules/ohmyfetch/node_modules/node-fetch@3.2.3
```

**Comment by lukaszflorczak** [comment]
Today I tried Nuxt 3 rc.2 and I have the same error also on `pnpm`. It looks like only `yarn` is working.

**Comment by larbish** [comment]
@lukaszflorczak For the moment, you should stay with `nuxt-rc.1` => https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.2. 

However, I just upgrade the module deps and it works on `pnpm` and `yarn` for me with the rc.1. You can try with the last published version `0.1.11` of the module. I'll keep the module updated (and try with `pnpm`) as soon as the new rc is available.
