### ISSUE TITLE
Realtime feature

### ISSUE THREAD

**Issue by ColinEspinas** [nuxt-community/supabase-module#40]
Just trying to use basic realtime features within a Vue component like so:
```vue
<script lang="ts" setup>
import type { WorkEvent } from '~/types/event';
const supabase = useSupabaseClient();
const props = defineProps<{ event: WorkEvent; }>();

const { data: count } = await useAsyncData('votes-count', async () => {
  const { count } = await supabase.from('user-votes').select('*', { count: 'exact' }).eq('event', props.event.id);
  return count;
});

supabase.from('user-votes').on('*', () => {
    refreshNuxtData('votes-count');
}).subscribe();

</script>

<template>
  <NuxtLink
    :to="`/dashboard/events/${props.event.id}`"
  >
    <div class="card card-compact w-full bg-base-100">
      <div class="card-body">
        <h2 class="card-title line-clamp-1">
          {{ props.event.name }}
        </h2>
        <p class="line-clamp-3">
          {{ props.event.description }}
        </p>
        <div class="card-actions">
          <div class="badge">
            {{ count }} votes
          </div>
        </div>
      </div>
    </div>
  </NuxtLink>
</template>
```

But this does not work and throws a `Cannot read properties of undefined (reading 'event')` error the moment I try to use the subscribe feature.

Is there a way to get those feature working or is this out of the scope of this module for now?

**Comment by larbish** [comment]
Hey @ColinEspinas, I did not use the realtime feature for the project I made this module for. That's why it is not working with the module currently. However, it is a great feature from Supabase and I'd love to make it work ! Feel free to propose anything, I'll be happy to help. I tag this issue as `feature` to keep it in mind :)

**Comment by amrnn90** [comment]
Try wrapping the subscription inside an `onMounted` hook:
```ts
let subscription;

onMounted(() => {
  subscription = supabase.from('user-votes').on('*', () => {
      refreshNuxtData('votes-count');
  }).subscribe();
})
```
Also make sure to unsubscribe on unmount:
```ts
onUnmounted(() => {
  supabase.removeSubscription(subscription);
});
```

And make sure you have turned on the [Real Time API](https://supabase.com/docs/guides/api#realtime-api-1) for your table.

**Comment by ColinEspinas** [comment]
Seems to work, thanks a lot @amrnn90, have a great day.

I will not close the issue as I don't know what @larbish had in mind when he wanted to add those features into the module.

But it works and my issue is resolved.

**Comment by larbish** [comment]
Thanks @amrnn90, I've added an example in the `advanced` section of the doc.

**Comment by amrnn90** [comment]
No problem @larbish,
I took a look at the docs and I believe you forgot to add the `onMounted` hook:

https://github.com/nuxt-community/supabase-module/blob/656cd77f65ed2986029067166c899042a3230b2b/docs/content/4.advanced.md?plain=1#L27-L35

I made PR #48 to add it.

**Comment by larbish** [comment]
Indeed ! Thanks !
